deps: downgrade libc temporary for the compatibility with egui
$ cargo build

    Updating git repository `https://github.com/youngjoon-lee/wasm-timer.git`
error: failed to select a version for `libc`.
    ... required by package `libp2p-tcp v0.40.0 (https://github.com/youngjoon-lee/rust-libp2p.git?branch=gossipsub-wasm#69cf8913)`
    ... which satisfies git dependency `libp2p-tcp` of package `libp2p v0.52.0 (https://github.com/youngjoon-lee/rust-libp2p.git?branch=gossipsub-wasm#69cf8913)`
    ... which satisfies git dependency `libp2p` of package `jiri-core v0.0.1 (/Users/yjlee/repos/jiri/core)`
    ... which satisfies path dependency `jiri-core` (locked to 0.0.1) of package `jiri-standalone v0.0.1 (/Users/yjlee/repos/jiri/standalone)`
versions that meet the requirements `^0.2.143` are: 0.2.144, 0.2.143

all possible versions conflict with previously selected packages.

  previously selected package `libc v0.2.142`
    ... which satisfies dependency `libc = "^0.2"` (locked to 0.2.142) of package `android-activity v0.4.1`
    ... which satisfies dependency `android-activity = "^0.4"` (locked to 0.4.1) of package `egui-winit v0.21.1`
    ... which satisfies dependency `egui-winit = "^0.21.1"` (locked to 0.21.1) of package `eframe v0.21.3`
    ... which satisfies dependency `eframe = "^0.21.0"` (locked to 0.21.3) of package `jiri-web v0.0.1 (/Users/yjlee/repos/jiri/web)`

failed to select a version for `libc` which could resolve this conflict